### ISSUE TITLE
[3004]下载失败：磁盘读写错误

### ISSUE THREAD

**Issue by caojunJackson** [czy1121/update#37]
java.io.FileNotFoundException: /56cf48f10e4cf6043fbf53bbbc4009e3: open failed: EROFS (Read-only file system)
     at libcore.io.IoBridge.open(IoBridge.java:409)
     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:118)
     at ezy.boost.update.UpdateDownloader$LoadingRandomAccessFile.<init>(UpdateDownloader.java:236)
     at ezy.boost.update.UpdateDownloader.download(UpdateDownloader.java:184)
     at ezy.boost.update.UpdateDownloader.doInBackground(UpdateDownloader.java:78)
     at ezy.boost.update.UpdateDownloader.doInBackground(UpdateDownloader.java:34)
     at android.os.AsyncTask$2.call(AsyncTask.java:288)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)
 Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
     at libcore.io.Posix.open(Native Method)
     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
     at libcore.io.IoBridge.open(IoBridge.java:393)
 	... 11 more

**Comment by caojunJackson** [comment]
小米5.0以下系统 , 强制更新后不安装,清除缓存会报出此问题

**Comment by caojunJackson** [comment]
原因是mContext.getExternalCacheDir()返回null
