### ISSUE TITLE
安装APK报错

### ISSUE THREAD

**Issue by deerGentler** [czy1121/update#86]
UncaughtException detected: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/5DE0-1EEF/Android/data/com.lanbeiqianbao.gzt/cache/cf1e357a32341eef66f42a9dd5c684e3.apk
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:712)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:401)
        at ezy.boost.update.UpdateUtil.install(UpdateUtil.java:111)
        at ezy.boost.update.UpdateAgent.doInstall(UpdateAgent.java:251)
        at ezy.boost.update.UpdateAgent.doCheckFinish(UpdateAgent.java:231)
        at ezy.boost.update.UpdateAgent$1.onPostExecute(UpdateAgent.java:209)
        at ezy.boost.update.UpdateAgent$1.onPostExecute(UpdateAgent.java:197)
        at android.os.AsyncTask.finish(AsyncTask.java:727)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by zhengdj** [comment]
@deerGentler 我也碰到这个问题了，你怎么解决的？
